version: '3.8'

services:
  mon-projet-vue:
    image: php:8.2-apache
    container_name: bubbles
    volumes:
      - ./src:/var/www/html
    environment:
      - VIRTUAL_HOST=bubbles.tiphereth.site,www.bubbles.tiphereth.site
      - LETSENCRYPT_HOST=bubbles.tiphereth.site,www.bubbles.tiphereth.site
      - LETSENCRYPT_EMAIL=admin@tiphereth.site
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    external: true
